In Python we have `lists` that serve the purpose of `arrays`, but they are slow to process.

NumPy aims to provide an array object that is up to `50x faster` than traditional Python lists.

The array object in NumPy is called `ndarray`, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in `machine learning` and `data science`, where speed and resources are very important.

Importing `Numpy`

In [4]:
import numpy as np
np.__version__

'1.26.2'

Creating `Arrays`

In [20]:
arr = np.array([[[0,2,3], [8,9,7]], [[0,2,3], [8,9,7]]])
arr

array([[[[[0, 2, 3],
          [8, 9, 7]],

         [[0, 2, 3],
          [8, 9, 7]]]]])

`Dimension` of Array

In [22]:
arr.ndim

arr = np.array([[[0,2,3], [8,9,7]], [[0,2,3], [8,9,7]]], ndmin = 5)
arr.ndim

5

`Indexing` the Array

In [49]:
arr1 = np.array([1,2,3])
arr[0]

arr2 = np.array([[1,2,3], [4,5,6]])
# arr2[1][1]
arr2[1,1]
arr2[1,-3]

4

Array `Slicing`

In [63]:
arr1 = np.array([1,2,3,4,5,6])

arr1[1:4]
arr1[-3:-1]

#Steps 

arr1[1:5:2]
arr1[::2]

array([1, 3, 5])

Slicing `2-D Array`

In [68]:
arr2 = np.array([[1,2,3], [4,5,6]])

arr2[1, 1:3]

array([5, 6])

Array `Datatypes`

In [74]:

arrN = np.array([1.7, 12])

arrN.dtype

arrN = np.array([1.7, 12], dtype='i8')

arrN.dtype

dtype('int64')

`COPY` vs `VIEW`

`copy` do not makes changes to original array when copied array data is changed and vice verse

`view` make changes to original array when viewed array data is changed and vice verca

In [76]:
arr = np.array([1,2,3,4,5])
x = arr.copy()

arr[0] = 45

print(arr)
print(x)

[45  2  3  4  5]
[1 2 3 4 5]


In [77]:
arr = np.array([1,2,3,4,5])
x = arr.view()

arr[0] = 45

print(arr)
print(x)

[45  2  3  4  5]
[45  2  3  4  5]


Array `Shape`

In [96]:
arr1 = np.array([1,2,3,4,5,6,7,8])
arr1.shape

arr1.reshape(2,2,2)

arr1.reshape(2,2,-1) #One Unknown Dimension

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

Array `Flattening`

In [97]:
arr2 = np.array([[1,2,3], [4,5,6]])

arr2.reshape(-1)

array([1, 2, 3, 4, 5, 6])

Array `Iteration`

In [100]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([[1,2,3], [4,5,6]])

for arr in arr1:
    print(arr)
for arr in arr2:
    print(arr)

1
2
3
4
5
6
[1 2 3]
[4 5 6]


Iterating `2-D Array`

In [101]:
for x in arr2:
    for y in x:
        print(y)

1
2
3
4
5
6


Iterating through `nditer`

In [103]:
for x in np.nditer(arr2):
    print(x)

1
2
3
4
5
6


Array `Concatenation`

In [105]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5])

print(np.concatenate((arr1,arr2)))

[1 2 3 4 5]


Array `Splitting`

In [109]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])

print(np.array_split(arr1,4))
#Will return list of 4 arrays

[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


Array `Searching`

In [113]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])

print(np.where(arr1 == 8))
print(np.where(arr1 % 2))

(array([7], dtype=int64),)
(array([0, 2, 4, 6, 8], dtype=int64),)


Give index where it has to be inserted in sorted array

In [120]:
arr1 = np.array([1,2,3,4,5,6,8,9])

np.searchsorted(arr1, 7)

6

Array `Sorting`

In [122]:
arr3 = np.array([3,1,7,2])

np.sort(arr3)


array([1, 2, 3, 7])

Can Perform More operations on the array like `Random Permutation`, `Normal`,`Binomial` and `Poisson` Distribution and much more using various other libraries like `seaborn`, `pandas` , etc which we will discuss in our upcoming videos